### ISSUE TITLE
Changing data format

### ISSUE THREAD

**Issue by linux4life798** [OpenChirp/mqtt_influx_storage_service#2]
There needs to be some way to change the data format or reset the data format for a transducer.

It happens much too often that someone accidentally publishes some bogus string and then all numeric values are then ignored. Maybe some form of warning?

This could be somewhat ignored if we can move simple last values into the OC core.

**Comment by ABalanuta** [comment]
We can add a Transducer type that is automatically filled on creation. But if changed it will reset the transducer type. We can do this by displaying a nice big warning that the data will be deleted.
